### PR TITLE
Test Preview of Firebase Hosting configuration

### PR DESCRIPTION
**Pull request by glasnt**
Using a combination of: 

 * https://firebase.google.com/docs/hosting/github-integration
 * https://github.com/GoogleCloudPlatform/devrel-demos/tree/main/app-dev/jamstack-frameworks-firebase-hosting/lektor

Project being used is temporary, just for this test.

### CODE REVIEW

**Review by freakboy3742 — COMMENTED** [review]
If I'm reading this right, this is managing both the deploy *and* the preview? I presume we could use only the `build-and-preview` workflow without breaking anything? Or would a firebase setup require that we move off Github Pages for main site hosting?

**Comment by glasnt** [comment]
This was just the default configuration, where it presumes you're using the deployment previews for your live sites on Firebase Hosting, sort of how we currently use Netlify for previews and GitHub Pages for hosting. 

I presume we could remove the `.github/workflows/firebase-hosting-merge.yml` and the `.github/workflows/ci.yml` and just have a Firebase Hosting-based preview and a GitHub Pages-based deploy. 

But I'd absolutely want to double-check costs as we don't currently have any Google Cloud infra and I don't want to accidentally the entire budget.

**Comment by freakboy3742** [comment]
Yeah - unless there's a genuine no-credit-card "free" tier, preference would be to stick to AWS so I've only got a single bill attached to a credit card.

**Comment by glasnt** [comment]
To fix the `PendingDeprecationWarning`:  https://github.com/fschulze/lektor-rst/pull/12

The rendered `output/` is 167MB, but only 36.5MB is uploaded (since a lot of the size is Lektor state files in dot folders which Firebase ignores by default). I only got this because I did a deployment, rather than a preview. Until now my one preview wasn't appearing as storage size spent.  (I'm also looking into why it's still a chonky 36.5MB)

The "Spark" plan is zero cost, https://firebase.google.com/pricing, and even if it was on the paid plan, it'd be $0.02/GB. 

I'll triple-check you can have a Spark account without a billing instrument.

**Comment by glasnt** [comment]
In Hosting > Release History > Release Storage settings, you can limit the the amount of previous releases to keep 

Screen Shot 2022-10-13 at 11 52 05 am

This relates to releases, but we won't be using those, just previews. 

I also found Sagi's profile pic was many megabytes; will submit a PR to reduce that in the main repo.

**Pull request closed without merging**
